### ISSUE TITLE
Problems with Batching and TracerSdkProvider

### ISSUE THREAD

**Issue by litscher** [newrelic/opentelemetry-exporter-java#30]
TracerSdkProvider: It appears that the README is out of date with yesterday's update of Opentelemetry. 

For the batching problems, we are seeing spans being created and then the processor and exporter are failing. This code worked before the updates from yesterday. 
```
io.opentelemetry.sdk.trace.export.BatchSpansProcessor$Worker$2 run
WARNING: Exception thrown by the export.
java.lang.AbstractMethodError: Receiver class com.newrelic.telemetry.opentelemetry.export.NewRelicSpanExporter does not define or inherit an implementation of the resolved method abstract export(Ljava/util/List;)Lio/opentelemetry/sdk/trace/export/SpanExporter$ResultCode; of interface io.opentelemetry.sdk.trace.export.SpanExporter.
	at io.opentelemetry.sdk.trace.export.BatchSpansProcessor$Worker$2.run(BatchSpansProcessor.java:397)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by jkwatson** [comment]
Hi @litscher ! We're working on getting everything up to date for the 0.3.0 release. This is fixed on master, but we haven't published it yet. So, if you force-refresh your gradle dependencies, this *should* be working for you.

**Comment by litscher** [comment]
We are still seeing errors after creating new images with docker and new pods with Kubernetes

**Comment by jkwatson** [comment]
ok. I just opened up #31  to publish a new snapshot version and update the README. This is definitely still a work in progress, so bear with us as we get it all working.

**Comment by jkwatson** [comment]
@litscher we've published 0.3.0-SNAPSHOT of the open telemetry reporter. It should be fully compatible with 0.3.0 of the open telemetry java project. Can you give it a try?

**Comment by litscher** [comment]
Looks like things are happier. Thank you!

**Comment by jkwatson** [comment]
Great! Glad it's working!
